name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'main'
    - 'dev'

env:
  SOURCE_DIR:     ${{ github.workspace }}
  ARTIFACT:       firmware

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
    - name: Install platformIO libraries
      run: pio lib install
    - name: Run PlatformIO
      run: platformio run
    - name: move firmware
      run: |
        mkdir firmware
        mv .pio/build/macropad/firmware.uf2 firmware/firmware_macropad.uf2
        mv .pio/build/keyboard/firmware.uf2 firmware/firmware_keyboard.uf2
        mv .pio/build/vmi/firmware.uf2 firmware/firmware_vmi.uf2
    - name: Save build result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT }}
        path: firmware